data_ingestion:
  test_size: 0.12
model_training:
  models:
    LogisticRegression:
      enabled: true
      max_iter: 700
    SVC:
      enabled: false
      kernel: rbf
      probability: true
    RandomForestClassifier:
      enabled: true
      n_estimators: 270
      min_samples_split: 8
    KNeighborsClassifier:
      enabled: true
      n_neighbors: 4
    XGBClassifier:
      enabled: true
      n_estimators: 280
      use_label_encoder: false
      eval_metric: logloss
